spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exemptionsdb
    username: exemptions
    password: exemptions
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.highlight_sql: true
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none   # Flyway controls schema
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.data.jpa.repository.query: DEBUG
    org.hibernate.orm.jpa: DEBUG
